---
- name: Install NGINX
  package:
    name: nginx
    state: present

- name: Copy NGINX config
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Copy NGINX proxy config
  copy:
    src: "{{ role_path }}/files/proxy.conf"
    dest: "/etc/nginx/proxy.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Copy conf.d configs
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item | basename }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_fileglob: conf.d/*

- name: Enable NGINX
  systemd:
    name: nginx
    enabled: true
    state: restarted
