---
- name: Create library directory
  file:
    path: "/storage/container/jellyfin"
    state: directory
    owner: "tryton-vanmeer"
    group: "tryton-vanmeer"
    mode: "0775"

- name: Jellyfin Container
  vars:
    container_image: "docker.io/linuxserver/jellyfin"
    container_name: "jellyfin"
    container_run_args: >-
      -e PUID=1000
      -e PGID=1000
      -e TZ=America/Toronto
      -p 8096:8096
      -v /storage/container/jellyfin:/config:Z
      -v /storage/media:/data
  import_role:
    name: "podman-container-systemd"