---
- name: Install Transmission
  package:
    name: transmission-daemon
    state: present

- name: Set a higher value for rmem_max
  sysctl:
    name: "net.core.rmem_max"
    value: "4194304"
    state: present

- name: Set a higher value for rmem_max
  sysctl:
    name: "net.core.wmem_max"
    value: "1048576"
    state: present

- name: Enable transmission-daemon
  systemd:
    name: transmission-daemon
    enabled: true
    state: started

- name: Disable rpc-whitelist
  json_patch:
    src: "/var/lib/transmission/.config/transmission-daemon/settings.json"
    operations:
      - op: replace
        path: "/rpc-whitelist-enabled"
        value: "false"
