---
- name: Install Transmission
  package:
    name: transmission-daemon
    state: present

- name: Enable transmission-daemon
  systemd:
    name: transmission-daemon
    enabled: true

- name: Disable rpc-whitelist
  json_patch:
    src: "/var/lib/transmission/.config/transmission-daemon/settings.json"
    operations:
      - op: replace
        path: "/rpc-whitelist-enabled"
        value: "false"
